name: "CNNModel"
pretrained_model_path: null # Path to pretrained model (if any)
params:
  trainer_name: "CNNTrainer"
  type: "convDL" # Type of model (convML for conventional machine learning, convDL for conventional deep learning and LLM for large language models)
  save_checkpoint: 1 # Save checkpoint every n epochs. Set to 0 to disable.
  output_shape: 1
  kernel_size: 1
  pool_size: 2
  learning_rate: 0.001
  num_epochs: 100
  verbose: 2 # Controls verbosity of output (0 = silent, 1 = log every 10 batches, 2 = log every batch)
  early_stopping_rounds: 10 # Number of rounds for early stopping
