name: "GRUModel"
params:
  # Basic configuration
  trainer_name: "GRUTrainer"
  
  # Training parameters
  num_epochs: 60
  patience: 5
  use_cuda: true
  save_checkpoint: 5
  
  # Model architecture
  model_architecture:
    hidden_dim: 256
    layer_dim: 2
    dropout_rate: 0.3
  
  # Optimizer settings
  optimizer:
    name: "adam"
    learning_rate: 0.0001
    weight_decay: 1e-6
  
  # Scheduler settings
  scheduler:
    factor: 0.5
    patience: 3
    min_lr: 1e-6