name: "LSTMModel"
params:
  trainer_name: "LSTMTrainer"
  save_checkpoint: 1 # Save checkpoint every n epochs. Set to 0 to disable.
  num_features: 101
  output_shape: 1
  num_channels: 1
  kernel_size: 3
  pool_size: 2
  learning_rate: 0.001
  num_epochs: 10
  verbose: 2 # Controls verbosity of output (0 = silent, 1 = log every 10 batches, 2 = log every batch)
