name: "LSTMModel"
pretrained_model_path: null # Path to pretrained model (if any)
params:
  trainer_name: "LSTMTrainer"
  type: "DL" # Type of model (ML for machine learning, DL for deep learning)
  save_checkpoint: 0 # Save checkpoint every n epochs. Set to 0 to disable.
  num_layers: 3 # Number of LSTM layers
  output_shape: 1
  hidden_size: 256 # Number of hidden units in LSTM layers
  learning_rate: 0.001
  num_epochs: 100
  early_stopping_rounds: 5
  dropout: 0.2 # Dropout rate for LSTM layers
  verbose: 2 # Controls verbosity of output (0 = silent, 1 = log every 10 batches, 2 = log every batch)
