# Configuration file for pulse benchmark

# General settings
general:
  app_name: "Pulse"
  version: "1.0.0"
  debug_mode: true
  debug_data_length: 100 # Number of rows used if debug_mode is true
  debug_logging: true # false: logging level DEBUG, true: logging level INFO
  use_scratch: true

# Weight and Biases (wandb) logging configuration
wandb:
  enabled: false
  entity: "berner"

###### Application specific settings ######
base_path: "/cluster/project/bmds_lab/sepsis_jan/pulse" #"/cluster/project/bmds_lab/sepsis_sophia/pulse" # #"/path/to/pulse"

# Tasks to process
tasks:
  # - "mortality"
  - "aki"
  # - "sepsis"

# Datasets to process
dataset_path: datasets/original_harmonized #"/path/to/datasets"
datasets:
  # - "hirid"
  - "miiv"
  # - "eicu"

# _______ Preprocessing Baseline _______

# Random seed for reproducibility
random_seed: 42

# Options for preprocessing
preprocessing_baseline:
  replace_outliers: true # Whether to replace outliers with NaNs
  flag_na: true # Whether to flag NA values with binary indicators
  standardize: false # Whether to standardize features (yes: convDL, not required: convML, LLM)
  static_imputation: true # Whether to perform static feature imputation
  dynamic_imputation: true # Whether to perform dynamic feature imputation
  save_data: true # Whether to save preprocessed data
  split_ratios: # Train/Val/Test split ratios
    train: 0.8
    val: 0.1
    test: 0.1
    test_limited: 50 # Number of stay_ids for limited test set, null = test set is not limited

# _______ Preprocessing Advanced _______

preprocessing_advanced:
  windowing:
    enabled: true # Enable/disable windowing
    data_window: 6 # Size of the data window
    prediction_window: 0 # Size of the prediction window (0 = predict at the end of window)
    step_size: 1 # Step size for sliding windows
    save_data: true # Whether to save windowed data

prompting:
  prompting_ids:
    # - "liu_2023_few_shot_preprocessor" # Preprocessing ID for the model
    # - "zhu_2024_is_larger_always_better_preprocessor"
    - "sarvari_2024_aggregation_preprocessor"
  shots: 0
  save_test_set: false # Whether to save the test set

  # TODO: change shots from model config to here

# _______ Model Training _______

benchmark_settings:
  batch_size: 100

load_models:
  # - model_configs/RandomForestModel.yaml
  # - model_configs/XGBoost.yaml
  # - model_configs/LightGBMModel.yaml
  # - model_configs/CNNModel.yaml
  # - model_configs/LSTMModel.yaml
  # - model_configs/InceptionTimeModel.yaml
  # - model_configs/GRUModel.yaml
  # - model_configs/Llama3.yaml
  # - model_configs/Llama4.yaml # Not tested...
  # - model_configs/Gemma.yaml # Not tested...
  # - model_configs/Meditron.yaml # Not working...
  - model_configs/DeepseekR1Model.yaml
