# Configuration file for pulse benchmark

# General settings
general:
  app_name: "Pulse"
  version: "1.0.0"
  debug_mode: true

# Weight and Biases (wandb) logging configuration
wandb:
  enabled: false
  entity: "berner"
  # experiment_name: "experiment_1"

# Application specific settings
benchmark_settings:
  batch_size: 100
  num_epochs: 10
  learning_rate: 0.001
  optimizer: "adam" # Options: adam, sgd, rmsprop

preprocessing:
  windowing_time: 60 # in minutes
  onset_matching: true

models:
  - name: "RandomForest"
    params:
      trainer_name: "RandomForestTrainer"
  # - name: "XGBoost"
  #   params:
  #     trainer_name: "XGBoostTrainer"
  #     n_estimators: 100
  #     learning_rate: 0.1
  #     max_depth: 3
  #     subsample: 0.8
  #     colsample_bytree: 0.8
  #     objective: "binary:logistic"
  # - name: "SimpleDLModel"
  #   params:
  #     trainer_name: "SimpleDLTrainer"
  #     input_size: 3
  #     hidden_size: 128
  #     output_size: 10

datasets:
  - "harmonized_icu"

tasks:
  - mortality
  - aki
  - sepsis
