# Configuration file for pulse benchmark

# General settings
general:
  app_name: "Pulse"
  version: "1.0.0"
  debug_mode: true

# Weight and Biases (wandb) logging configuration
wandb:
  enabled: false
  entity: "berner"
  # experiment_name: "experiment_1"

###### Application specific settings ######
base_path: "/Users/sophiaehlers/Documents/pulse" #"/path/to/pulse"

# Tasks to process
tasks:
  # - "mortality"
  - "aki"
  # - "sepsis"
  # - "harmonized_icu"

# Datasets to process
datasets:
  - "hirid"
  # - "miiv"
  # - "eicu"

# _______ Preprocessing _______

# Random seed for reproducibility
random_seed: 42

# Options for preprocessing
preprocessing:
  # Whether to replace outliers with NaNs
  replace_outliers: true
  
  # Whether to flag NA values with binary indicators
  flag_na: true
  
  # Whether to standardize features
  standardize: true
  
  # Whether to save preprocessed data
  save_data: false
  
  # Train/Val/Test split ratios
  split_ratios:
    train: 0.7
    val: 0.1
    test: 0.2


# _______ Model Training _______

benchmark_settings:
  batch_size: 100
  num_epochs: 10
  learning_rate: 0.001
  optimizer: "adam" # Options: adam, sgd, rmsprop

models:
  - name: "RandomForest"
    params:
      trainer_name: "RandomForestTrainer"
  # - name: "XGBoost"
  #   params:
  #     trainer_name: "XGBoostTrainer"
  #     n_estimators: 100
  #     learning_rate: 0.1
  #     max_depth: 3
  #     subsample: 0.8
  #     colsample_bytree: 0.8
  #     objective: "binary:logistic"
  # - name: "SimpleDLModel"
  #   params:
  #     trainer_name: "SimpleDLTrainer"
  #     input_size: 3
  #     hidden_size: 128
  #     output_size: 10
