name: "ClaudeSonnet4Model"
pretrained_model_paths: null # Path to pretrained model (if any)
params:
  trainer_name: "DummyTrainer"
  mode: "inference" # Mode of operation (inference, training)
  model_id: "ClaudeSonnet4" # Model ID, path to pretrained model (if any)
  type: "LLM" # Type of model (convML for conventional machine learning, convDL for conventional deep learning and LLM for large language models)
  verbose: 2
  max_new_tokens: 300
  max_length: 30000 # Maximum length of input sequences
  temperature: 0.4 # Temperature for sampling (0.0 = greedy sampling)
  thinking_budget: 0
