name: "Gemma3Model"
pretrained_model_path: null # Path to pretrained model (if any)
params:
  trainer_name: "GemmaTrainer"
  model_id: "google/medgemma-4b-it" # Model ID for Gemma, path to pretrained model (if any)
  type: "LLM" # Type of model (convML for conventional machine learning, convDL for conventional deep learning and LLM for large language models)
  verbose: 2
  tuning: false # Whether to use prompt tuning
  num_epochs: 10 # Number of epochs for training
  max_new_tokens: 200
  max_length: 20000 # Maximum length of input sequences
  do_sample: true # Whether to sample new tokens
  temperature: 0.4 # Temperature for sampling (0.0 = greedy sampling)
